attributes:
  metadata:
    group: 'other'
  dynatrace_tenant:
    type: "text"
    weight: 20
    value: ""
    label: "Environment ID"
    description: "Your Dynatrace environment ID"
    regex:
      source: '\S'
      error: "Environment ID must not be empty"
  dynatrace_token:
    type: "text"
    weight: 30
    value: ""
    label: "Token"
    description: "Your Dynatrace environment token"
    regex:
      source: '\S'
      error: "Token must not be empty"
  dynatrace_managed:
    value: false
    label: "Tick if you are using Dynatrace Managed"
    type: "checkbox"
    weight: 40
  dynatrace_server:
    value: ""
    label: "Dynatrace Managed IP/Domain"
    description: "Dynatrace Managed IP address or domain name"
    weight: 50
    type: "text"
    regex:
      source: '\S'
      error: "IP/Domain must not be empty"
    restrictions:
      - condition: "settings:dynatrace.dynatrace_managed.value == false"
        action: "hide"
