attributes:
  metadata:
    group: 'other'
  # Dynatrace environment ID
  dynatrace_tenant:
    type: "text"
    weight: 20
    value: ""
    label: "Environment ID"
    description: "Your Dynatrace environment ID"
    regex:
      source: '\S'
      error: "Environment ID must not be empty"
  # Dynatrace environment token
  dynatrace_token:
    type: "text"
    weight: 30
    value: ""
    label: "Token"
    description: "Your Dynatrace environment token"
    regex:
      source: '\S'
      error: "Token must not be empty"
  # Dynatrace Server URL
  dynatrace_server:
    type: "text"
    weight: 40
    value: ""
    label: "Dynatrace Server URL"
    description: "Use the URL provided in the OneAgent installation screen"
    regex:
      source: '\S'
      error: "Server URL must not be empty"
