attributes:
  #metadata:
    # Settings group can be one of "general", "security", "compute", "network",
    # "storage", "logging", "openstack_services" and "other".
    #group: 'other'

  ruxit_tenant:
    type: "text"
    weight: 20
    value: ""
    label: "Dynatrace Ruxit Tenant ID"
    description: "Dynatrace Ruxit Tenant ID description"
    regex:
      source: '\S'
      error: "Dynatrace Ruxit Tenant ID must not be empty"

  ruxit_token:
    type: "text"
    weight: 30
    value: ""
    label: "Dynatrace Ruxit Token"
    description: "Dynatrace Ruxit Token description"
    regex:
      source: '\S'
      error: "Dynatrace Ruxit Token must not be empty"
