attributes:
  metadata:
    group: 'other'

  ruxit_tenant:
    type: "text"
    weight: 20
    value: ""
    label: "Ruxit Environment ID"
    description: "Ruxit Environment ID description"
    regex:
      source: '\S'
      error: "Ruxit Environment ID must not be empty"

  ruxit_token:
    type: "text"
    weight: 30
    value: ""
    label: "Ruxit Token"
    description: "Ruxit Token description"
    regex:
      source: '\S'
      error: "Ruxit Token must not be empty"
