attributes:
  metadata:
    group: 'other'
  dynatrace_tenant:
    type: "text"
    weight: 20
    value: ""
    label: "Environment ID"
    description: "Your Dynatrace environment ID"
    regex:
      source: '\S'
      error: "Environment ID must not be empty"
  dynatrace_token:
    type: "text"
    weight: 30
    value: ""
    label: "Token"
    description: "Your Dynatrace environment token"
    regex:
      source: '\S'
      error: "Token must not be empty"
